name: Web Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Run workflow on push to main branch

  pull_request:
    branches:
      - main  # Run on pull request events targeting main branch

  workflow_dispatch:  # Allows manual execution from GitHub Actions tab

concurrency:
  group: "pages"
  cancel-in-progress: false  # Ensures ongoing deployments complete before new ones start

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.8
  FLET_CLI_VERSION: 0.27.5
  PYTHONUTF8: 1  # Ensures UTF-8 encoding
  FLET_CLI_NO_RICH_OUTPUT: 1  # Disables rich output formatting
  UV_NO_PROGRESS: 1  # Disables UV progress bars

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet-cli==$FLET_CLI_VERSION
          pip install watchdog==4.0.0  # Fix missing watchdog issue

      - name: Build Flet Web App
        run: |
          echo "Repository: ${GITHUB_REPOSITORY}, User: ${GITHUB_REPOSITORY%/*}, Base URL: ${GITHUB_REPOSITORY#*/}"
          flet build web --base-url "/myapp/" --route-url-strategy hash

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: web-build-artifact
          path: build/web  # Ensure correct path to built files

  deploy:
    needs: build  # Runs after the "build" job

    runs-on: ubuntu-latest

    permissions:
      pages: write  # Allow deployment to GitHub Pages
      id-token: write  # Verify deployment source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages 🚀
        if: github.event_name == 'push'  # Deploy only on push events
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: web-build-artifact  # Deploy the built web app
