name: Flet Web Build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.22.2

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || echo "No requirements.txt found, skipping..."

    - name: Setup Flutter (for Flet)
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Verify Repository Structure
      run: ls -la

    - name: Build Flet Web App
      run: flet build web --verbose  

    - name: Upload Web Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-build-artifact
        path: build/web  # Corrected path since "myapp" directory is removed
        if-no-files-found: warn
        overwrite: false
